# Reject requests by IP or unrecognized Host
server {
    listen 80 default_server;
    server_name _;
    return 444;
}

server {
    listen 80;
    server_name www.simon-wong.cn;

    root /var/www/html;

    location /intent-compiler/ {
        try_files $uri $uri/ /intent-compiler/index.html;
    }
}
